package io.mixeway.mixewayflowapi.integrations.scanner.sast.service;

public enum PolicyProfile {
    STRICT_SOURCE_TO_SINK,
    WEAK_CRYPTO_STRICT,
    LOGGING_CONTENT_AND_AUDIENCE,
    TIMING_SIDE_CHANNEL,
    SECRET_HANDLING,
    COOKIE_SECURITY,
    CONFIGURATION_REVIEW,
    DESERIALIZATION_REVIEW,
    ACCESS_CONTROL_REVIEW,
    TRANSPORT_SECURITY,
    XSS_CONTEXTUAL_ESCAPING,
    PATH_CANONICALIZATION,
    GENERAL_REVIEW
}
