# Use the official Nginx image from the Docker Hub
FROM nginx:alpine

# Copy the custom Nginx configuration file to the container
COPY nginx-dev.conf /etc/nginx/nginx.conf

# Expose port 80 to the host
EXPOSE 80