# Production environment configuration
server.port=8443
server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=/etc/pki/certificate.p12
server.ssl.key-store-password=${P12PASS}
server.ssl.key-alias=flow

# Encryption settings
encryption.algorithm=AES
encryption.api-key-secret=Q9+6E7bFZJQJ4g4NhwFZKxkYoL1p8H3VuG6Y7DskMTA=

