spring.datasource.url=jdbc:postgresql://localhost:5432/flow

# Encryption settings
encryption.algorithm=AES
encryption.api-key-secret=3eK1Zldj6fvyH9kZLcfK1E6z5Y9J4BRqxEK2z1WZ2Rc=

logging.level.root=INFO
