spring.security.oauth2.client.registration.sso.client-id=flow
spring.security.oauth2.client.registration.sso.client-secret=ZPTAyJ053tdwqN2hzGCzSJtRD34vomVY
spring.security.oauth2.client.registration.sso.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.sso.redirect-uri=http://localhost:8888/api/v1/sso
spring.security.oauth2.client.registration.sso.scope=openid,profile,email
spring.security.oauth2.client.provider.sso.authorization-uri=http://localhost:8080/realms/test/protocol/openid-connect/auth
spring.security.oauth2.client.provider.sso.token-uri=http://localhost:8080/realms/test/protocol/openid-connect/token
spring.security.oauth2.client.provider.sso.user-info-uri=http://localhost:8080/realms/test/protocol/openid-connect/userinfo
spring.security.oauth2.client.provider.sso.jwk-set-uri=http://localhost:8080/realms/test/protocol/openid-connect/certs
spring.security.oauth2.client.provider.sso.user-name-attribute=preferred_username