# Production environment configuration
server.port=8443
server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=/etc/pki/certificate.p12
server.ssl.key-store-password=${P12PASS}
server.ssl.key-alias=flow

frontend.url=${FRONTEND_URL}

# OAuth2 Configuration - SSO
spring.security.oauth2.client.registration.sso.client-id=${SSO_CLIENT_ID}
spring.security.oauth2.client.registration.sso.client-secret=${SSO_CLIENT_SECRET}
spring.security.oauth2.client.registration.sso.redirect-uri=${SSO_REDIRECT_URI}
spring.security.oauth2.client.provider.sso.authorization-uri=${SSO_AUTHORIZATION_URI}
spring.security.oauth2.client.provider.sso.token-uri=${SSO_TOKEN_URI}
spring.security.oauth2.client.provider.sso.user-info-uri=${SSO_USER_INFO_URI}
spring.security.oauth2.client.provider.sso.jwk-set-uri=${SSO_JWK_SET_URI}

# Constant OAuth2 Properties
spring.security.oauth2.client.registration.sso.scope=user:email,read:user
spring.security.oauth2.client.registration.sso.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.sso.user-name-attribute=email

